Repository_Generic/Repository/DesignPatterns.ASP/Models/ErrorViewModel.cs
namespace DesignPatterns.ASP.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Repository_Generic/Repository/DesignPatterns.ASP/Controllers/BeerController.cs
using DesignPatterns.ASP.ViewsModel;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Patterns.UnitOW.Entities;
using UnitOffWork;

namespace DesignPatterns.ASP.Controllers
{
    public class BeerController : Controller
    {
        private readonly IUnitOffWork _unitOffWork;

        public BeerController(IUnitOffWork unitOffWork)
        {
            _unitOffWork = unitOffWork;
        }
        public IActionResult Index()
        {

            IEnumerable<BeerViewModel> beers =
                from d in _unitOffWork.Beers.Get()
                select new BeerViewModel
                {
                    BeerId = d.BeerId,
                    Name = d.Name,
                    Style = d.Style
                };
            return View("Index", beers);
        }

        [HttpGet]
        public IActionResult Add()
        {

            var brands = _unitOffWork.Brands.Get();
            ViewBag.Brands = new SelectList(brands, "BrandId", "Name");
            return View();
        }

        [HttpPost]
        public IActionResult Add(FormBeerViewModel beerVM)
        {

            if (!ModelState.IsValid)
            {
                var brands = _unitOffWork.Brands.Get();
                ViewBag.Brands = new SelectList(brands, "BrandId","Name");
                return View("Add", beerVM);
            }

            var beer = new Beer();
            beer.Name = beerVM.Name;
            beer.Style = beerVM.Style;

            if (beerVM.BrandId == null)
            {
                var brand = new Brand();
                brand.Name = beerVM.OtherBrand;
                brand.BrandId = Guid.NewGuid();
                beer.BrandId = brand.BrandId;
                _unitOffWork.Brands.Add(brand);
            }
            else
            {
                beer.BrandId = (Guid)beerVM.BrandId;
            }

            _unitOffWork.Beers.Add(beer);
            _unitOffWork.Save();

            return RedirectToAction("Index");
        }





    }
}

Repository_Generic/Repository/DesignPatterns.ASP/Controllers/HomeController.cs
using DesignPatterns.ASP.Models;
using DesignPatterns.Respository;
using Microsoft.AspNetCore.Mvc;
using Patterns.UnitOW.Entities;
using System.Diagnostics;

namespace DesignPatterns.ASP.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        private readonly IRepository<Beer> _respository;
        public HomeController(ILogger<HomeController> logger, IRepository<Beer> repository)
        {
            _logger = logger;
            _respository = repository;
        }

        public IActionResult Index()
        {

            IEnumerable<Beer> lst = _respository.Get();

            return View("Index",lst);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Repository_Generic/Repository/DesignPatterns.ASP/Views/Beer/Add.cshtml
@model DesignPatterns.ASP.ViewsModel.FormBeerViewModel

<form asp-controller="Beer" asp-action="Add" method="post">

    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Style"></label>
        <input class="form-control" asp-for="Style" />
        <span asp-validation-for="Style" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="BrandId"></label>
        <select class="form-control" asp-for="BrandId"
                asp-items="@ViewBag.Brands">
            ---Selecciona algo---
        </select>
        <span asp-validation-for="BrandId" class="text-danger"></span>
    </div>



    <div class="form-group">
        <label asp-for="OtherBrand"></label>
        <input class="form-control" asp-for="OtherBrand" />
        <span asp-validation-for="OtherBrand" class="text-danger"></span>
    </div>


    <div class="form-group">
        <button class="btn btn-primary" type="submit">Guardar</button>
    </div>
</form>

Repository_Generic/Repository/DesignPatterns.ASP/Views/Beer/Index.cshtml
@using DesignPatterns.ASP.ViewsModel
@model IEnumerable<BeerViewModel>

<div class="row">
    <div class="col-12">
        <a class="btn btn-primary"
         href="~/Beer/Add">Nueva cerveza</a>
    </div>
</div>

<div class="row">
    <div class="col-12">
        <table class="table">
            <tr>
                <th>Nombre</th>
            </tr>
            @foreach(var beer in Model){
                <tr>
                    <td>@beer.Name</td>
                </tr>
            }
        </table>
    </div>
</div>

Repository_Generic/Repository/DesignPatterns.ASP/Views/Home/Index.cshtml
@using Patterns.UnitOW.Entities
@model IEnumerable<Beer>
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-12">
        @foreach(var beer in Model){
           <p>@beer.BeerId -</p>  <p>@beer.Name</p>
        }
    </div>
</div>

Repository_Generic/Repository/DesignPatterns.ASP/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DesignPatterns.ASP</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DesignPatterns.ASP.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">DesignPatterns.ASP</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - DesignPatterns.ASP - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>